/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_face_sdk_Context */

#ifndef _Included_com_face_sdk_Context
#define _Included_com_face_sdk_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_face_sdk_Context
 * Method:    destroyContext_jni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_destroyContext_1jni
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    getByIndex_jni
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_face_1sdk_Context_getByIndex_1jni
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_face_sdk_Context
 * Method:    getByKey_jni
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_face_1sdk_Context_getByKey_1jni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_face_sdk_Context
 * Method:    getOrInsertByKey_jni
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_face_1sdk_Context_getOrInsertByKey_1jni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_face_sdk_Context
 * Method:    copy_jni
 * Signature: (Lcom/face_sdk/Context;)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_copy_1jni
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    clone_jni
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_face_1sdk_Context_clone_1jni
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    setLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_setLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_face_sdk_Context
 * Method:    setDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_setDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_face_sdk_Context
 * Method:    setBool
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_setBool
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_face_sdk_Context
 * Method:    setString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_setString
  (JNIEnv *, jobject, jstring);


/*
 * Class:     com_face_sdk_Context
 * Method:    setDataPtr
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_setDataPtr
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_face_sdk_Context
 * Method:    pushBack_jni
 * Signature: (Lcom/face_sdk/Context;Z)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_Context_pushBack_1jni
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_face_sdk_Context
 * Method:    size
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_face_1sdk_Context_size
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isNone
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isNone
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isArray
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isArray
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isObject
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isObject
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isBool
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isBool
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isLong
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isLong
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isDouble
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isString
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isString
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    isDataPtr
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_isDataPtr
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_face_1sdk_Context_getLong
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_face_1sdk_Context_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    getBool
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_face_1sdk_Context_getBool
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_face_1sdk_Context_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_face_sdk_Context
 * Method:    getDataPtr
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_face_1sdk_Context_getDataPtr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
