/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_face_sdk_ProcessingBlock */

#ifndef _Included_com_face_sdk_ProcessingBlock
#define _Included_com_face_sdk_ProcessingBlock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_face_sdk_ProcessingBlock
 * Method:    process
 * Signature: (Lcom/face_sdk/Context;)V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_ProcessingBlock_process
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_face_sdk_ProcessingBlock
 * Method:    destroyProcessingBloc_jni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_face_1sdk_ProcessingBlock_destroyProcessingBloc_1jni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
